import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "./header"
import { CarrinhoContextProvider } from "./contexts/CartContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Patriton Modas",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <CarrinhoContextProvider>
                <body className={inter.className}>
                    <Header />
                    {children}
                </body>
            </CarrinhoContextProvider>
        </html>
    )
}
